# Generated by Django 4.0.5 on 2023-01-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilimits',
            name='limitType',
        ),
        migrations.AlterField(
            model_name='apilimits',
            name='apiKey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
