# Generated by Django 4.0.5 on 2023-01-18 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0002_remove_apilimits_limittype_alter_apilimits_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilimits',
            name='profile',
        ),
        migrations.AddField(
            model_name='apilimits',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
